# melpazoid <https://github.com/riscy/melpazoid> build checks.

# If your package is on GitHub, enable melpazoid's checks by copying this file
# to .github/workflows/melpazoid.yml and modifying RECIPE and EXIST_OK below.

name: melpazoid
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: nikolaik/python-nodejs:python3.10-nodejs24-bullseye
    steps:
      - uses: actions/checkout@v3
      # - uses: actions/setup-python@v5
      #   with:
      #     python-version: "3.13"
      - name: Install emacs
        run: |
          apt-get update
          apt-get install -y docker.io emacs-nox && emacs --version
      - name: Install
        env:
          ENV PIP_ROOT_USER_ACTION: ignore
        run: |
          python -m pip  install --upgrade pip
          git clone https://github.com/riscy/melpazoid.git ~/melpazoid
          pip install ~/melpazoid
      - name: Run
        env:
          LOCAL_REPO: ${{ github.workspace }}
          # RECIPE is your recipe as written for MELPA:
          RECIPE: (overleaf :fetcher github :repo "vale981/overleaf.el")
          # set this to false (or remove it) if the package isn't on MELPA:
          EXIST_OK: false
        run: echo $GITHUB_REF && make -C ~/melpazoid
